### PR TITLE
Feature: Determine correlations at subblock level

### PR DESCRIPTION
**Pull request by wdconinc**
This turned into a mostly harmless change that can get merged into develop. However, this does rely on feature-correlator-root-tree-output in #199 being merged firsts.

Note that this branch removes the cavity channels as dependent variables in the "new" correlation set. 

Note that this does not determine correlations between the subblocks.

Output, for example:
PlotByBlock 1296 A_xy
as obtained from
```
make -C build -j 2 && build/qwparity -c prex.conf -r 1296
root -l -q -b 'rootScripts/correlator/PlotByBlock.C("A_xy","blueR%d.%d.new.slope.root",1296)'
display PlotByBlock.1296.A_xy.png
```

### CODE REVIEW

**Comment by wdconinc** [comment]
Note: adding `block = 0` in the data handler map section file will result in using the hwsum, not block 0. That corresponds to the way we encode blocks in
```
Double_t QwVQWK_Channel::GetValue(size_t element) const {
    RangeCheck(element);
    if (element==0) return fHardwareBlockSum;
    return fBlock[element-1];
  }
```
but disagrees with what is used in the tree. It may make sense to revisit this. E.g. block outside 0-3 for hwsum and default = -1, then block = 0 for block0. @paulmking what do you think?

**Comment by paulmking** [comment]
I think you're right that using a "-1" to select the hw_sum in the correlators and letting the "block=0" mean the same thing as in the root file would make sense.

Or did you also intend to revist the block encoding in the QwVQWK_Channel class?

**Comment by wdconinc** [comment]
No, I wouldn't want to change the vqwk class encoding.

**Comment by wdconinc** [comment]
For run 2948 we now get the following:
image
Seems fishy in block0. Need to look in more detail. Hold off on merging.

**Comment by wdconinc** [comment]
Upon further inspection for run 2948 with some operations maps folded in we get:
* for the hw_sum:
image
* for the blocks:
image

This appears reasonable (no statement on consistent within uncertainties on the slopes), so I think @paulmking this is good for merging.

**Pull request merged**
