### PR TITLE
Feature online panguin

### PR DESCRIPTION
**Pull request by cipriangal**
This should work now. The scheme is to write the file on the disk -- with an ~1h circular tree --, have the trees autosaved every X number of events (see the conf file) and have panguin monitor the file and make plots. In the process I updated how panguin finds rootfiles in the QW_ROOTFILES folder.

The only issue that I see is that the drawing gets a bit funky when it updates. As far as I can tell this is not related to the monitoring functionality (will investigate sometime next week).

### CODE REVIEW

**Comment by wdconinc** [comment]
Is this the alternative to having panguin use the mapfile?

**Comment by paulmking** [comment]
This does result in a pretty significant performance hit in "online" mode, so we'll need to look into ways to minimize what we're saving (using the tree trimming) and see if we can get the performance back up.

See below for reference processing times for a 1000 second run.  On average, "online" mode is 10 times slower than "offline".  As I was watching the process, I could see the time per event grew as the root file grew:  at event 10000 (5.895 ms per event with 89.116% efficiency), at event 20000 (16.134 ms per event with 88.3187% efficiency), at event 30000 (28.611 ms per event with 88.0225% efficiency).

===Offline setting analysis of run 1423
30039 physics events were processed
CPU time used:  47.01 s (1.56497 ms per event)
Real time used: 50.7502 s (1.68948 ms per event)

==="Online" root file analysis of run 1423
30039 physics events were processed
CPU time used:  572.99 s (19.0749 ms per event)
Real time used: 644.113 s (21.4426 ms per event)

**Comment by cipriangal** [comment]
We didn't expect it to run any better than the actual offline, right? (because of the autosaving feature) 
I've made some quick tests and I think we still process events just fine at 30Hz (your math also says we are processing at 46Hz). 

So for now I'd be an advocate to just push this so people can make use of it until the end of APEX and in the mean time I'll work on a trimmed down version of the analyzer which hopefully will have a smaller hit on performance.

**Comment by paulmking** [comment]
@cipriangal No, but for an hour-long run, even at 30 Hz I would expect we would get non-functional performance toward the end.

 I'm about to add a tree_trim.in file that allows hw_sum and Device_Error_Code on all beamline devices and the SAMs, and with this the performance on 240 Hz octets in run 1410 (the most convenient long run I could find) seems to roughly plateau after 140000 events at 7-8 ms per event.  For 30 Hz quads the performance is likely slightly worse, but I expect it should still be under the 1/30 second needed to keep up with the data.  For 240 Hz, we'll need further trimming.

**Comment by cipriangal** [comment]
ok. we should probably kept this branch alive until we fix all the issues.

**Comment by paulmking** [comment]
Cip, I don't think these are "issues" so much as we need to make choices about what we want to have in the realtime tree.  The more data goes in, the less responsive the engine becomes.  If we keep "too much" we will end up missing "big" chunks of data, or freezing the DAQ, when we need to do the root writes.

Unless we can fork the writing process, I guess.  But that might need to go to a separate development branch.  We can discuss.  For now, I'll leave it open.

**Comment by wdconinc** [comment]
For what it's worth,
- Linking against --new and --glibs simultaneously is broken on all systems I tried and now matter how deep I dig. ROOT JIRA 9420 recommends disabling glibs to get new to work. No action on that bug report for several months.
- Problem seems to be with the system.rootrc setting Gui.Backend = native which is interpreted as x11 with higher priority than Qt which can also be set. See /usr/local/root/root.6.16.00/etc/plugins/TVirtualX/P040_TGQt.C. (https://root.cern.ch/root/htmldoc/guides/users-guide/ROOTandQt.html)
- In the case of qt it gets a bit further, but crashes on finding fonts.

**Pull request merged**
