### PR TITLE
Event datahandler

### PR DESCRIPTION
**Pull request by rr521111**
the bevington math now declares matricies to calculate the corrected y values and their errors.

includes a small change in the datahandlerarray class. it is renamed to datahandlerarrayhel. there is a duplicate class called datahandlerevt which was going to be single event datahandler.

the LRBcorrector now creates its variable list from a mapfile instead of the blue rootfile.

### CODE REVIEW

**Comment by wdconinc** [comment]
Too many changes to meaningfully review, I'm afraid. Can you first merge develop into the branch, and fix any conflicts (possibly none)?

**Comment by paulmking** [comment]
I remember now we wanted to split the changes to the correlator from the changes to the datahandlerarray in this branch.

**Comment by wdconinc** [comment]
Or maybe not. I guess Paul's update of the merge target fixed it...

**Comment by paulmking** [comment]
I'm going to close this pull request, and we can revisit the code changes seperately.

**Pull request closed without merging**
