### PR TITLE
Feature prex respin2 burp cut

### PR DESCRIPTION
**Pull request by cameronc137**
This initial set of commits assumes we want 0.6 mm cuts on all 4 target BPMs. I think I got every single file that doesn't have a reason to be any different, and I think I included 0.35 stability cut as well.

### CODE REVIEW

**Comment by cameronc137** [comment]
The meeting today suggests:

- Wait for W&M group's plots (which I'm currently re-spinning) to verify another decision about whether a larger burp cut hurts the non-modulating production data
- Do apply the burp cut retroactively to data < run 3900
- Change the amplitude of the burp cut only on the BPMs that matter (4eX, 4aY)
- Use a running value, based on Tao's results in http://ace.phys.virginia.edu/HAPPEX/4110

**Comment by cameronc137** [comment]
This branch should be used to increase BPM wire threshold burp cuts from 1000 to 2000

**Comment by leafybillow** [comment]
ADC burp threshold on BPM 11 and 12 wires should be raised to 2000 counts as well. Also, BPM 4eY and BPM 4aX position burp threshold should stay at 0.35 mm as suggested. @Gongzi-Zhang

**Comment by Gongzi-Zhang** [comment]
checked, everything should be fine now (though I didn't check the exact cut value for each cut)

**Comment by Gongzi-Zhang** [comment]
I also check the values, most values are reasonable to me, except one: bpm4a_ym:lower_limit being 10000 in files: prexCH_beamline_eventcuts.2948-.map,  prexCH_beamline_eventcuts.3139.map,   prexCH_beamline_eventcuts.3425-3428.map. while in other mapfiles, it is 1000. @leafybillow

**Comment by leafybillow** [comment]
> I also check the values, most values are reasonable to me, except one: bpm4a_ym:lower_limit being 10000 in files: prexCH_beamline_eventcuts.2948-.map, prexCH_beamline_eventcuts.3139.map, prexCH_beamline_eventcuts.3425-3428.map. while in other mapfiles, it is 1000. @leafybillow

@Gongzi-Zhang Thanks! It looks good to me as well. 10,000 ADC lower limit in BPM 4a YM has something to do with instrumental glitch in the early run. It is still well below beam-on ADC value and should be what we want.

**Pull request merged**
