### PR TITLE
Updating global event cuts for PREX respin 2 to include AT detectors

### PR DESCRIPTION
**Pull request by cameronc137**
Start caring about ATs, prior runs are often saturated - prex_maindet_eventcuts.3803-.map
Left arm only running - prex_maindet_eventcuts.3884-3893.map
Left arm only running - prex_maindet_eventcuts.4074-4077.map
Left arm only running - prex_maindet_eventcuts.4679-4690.map
ATs hardware blinded  - prex_maindet_eventcuts.4708-4939.map

All per Devi

### CODE REVIEW

**Comment by cameronc137** [comment]
http://ace.phys.virginia.edu/HAPPEX/4052

> 
"Using AT Device_Error_Code we would be loosing 13155 total multiplet patterns from our grand statistics which is ~1.5 miniruns."

**Comment by cameronc137** [comment]
Still outstanding is whether cuts on RHRS devices being local (RHRS turned off) should also remove devices and combos including RHRS devices from the corrolator maps?

**Comment by leafybillow** [comment]
> Still outstanding is whether cuts on RHRS devices being local (RHRS turned off) should also remove devices and combos including RHRS devices from the corrolator maps?

For those single arm runs with spectrometer down, I think we can keep bad arm detectors in the correlator as dependent variables without causing problem... if lower and upper detector channel limit is loose.  Also need to make sure blinder is not active on these channels for these runs.  

We also have a few runs where RHRS DAQ is offline. They may need to be removed from correlator ... I guess.

**Comment by leafybillow** [comment]
commit 0f21634bac574e993ffbbcecb1f76d25e8f152f9 
If I understand the purpose of grand correlator and overloaded regression correctly, we don't want independent variables(IV) in linear combination for a few reasons:
1. combined channel can always be reproduced from correlation of each individual elements; 
2. I think having combined channels and their raw channels in the same IV list is very likely to cause singular matrices. Or say the combined BPM is redundant to regression if raw elements already exist. 
 If we are really interested to know their correlation with other channels in an easy way, one dirty way is to put combined BPM in DV list instead of IV.  Or just create a separate correlator without (partial) overlapping BPMs.

**Pull request merged**
