### PR TITLE
Bugfix using TMapFile

### PR DESCRIPTION
**Pull request by wdconinc**
This can be merged in. Functionality seem to be complete (writes map file which can be read by qwcons consumer). Qwparity still crashes on closing (usually, sometimes it doesn't, not sure when it doesn't).

```
build/qwmockdatagenerator -r 10 -e :100000 --config qwparity_simple.conf --detectors mock_detectors.map
build/qwparity -r 10 --config qwparity_mapfile.conf
LD_PRELOAD=/usr/local/root/pro/lib/libNew.so rootScripts/mapfile/qwcons
```

### CODE REVIEW

**Comment by cipriangal** [comment]
Probably missing something super basic, but ...
On apar@adaq3:
```
-- The CXX compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
--     Install-prefix was at default -> forcing it to the source-dir
--     Use -DCMAKE_INSTALL_PREFIX=/usr/local to set to something else
-- System name Linux
-- Looking for MySQL and MySQL++ libraries.
--   Found MySQL++ library at /lib64/libmysqlpp.so
--   The "__USE_DATABASE__" flag is commented out in CMakeLists.txt; database support is DISABLED.
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   system
--   regex
-- Found ROOT: /adaqfs/apps/ROOT/6.14-04 (found suitable version "6.14.04", minimum required is "6.0") 
-- Adding check_git_repository target...
-- Git status has changed
-- Performing Test cxx-compiler-supports-pipe
-- Performing Test cxx-compiler-supports-pipe - Success
-- Performing Test cxx-compiler-supports-fsigned-char
-- Performing Test cxx-compiler-supports-fsigned-char - Success
-- Performing Test cxx-compiler-supports-fomit-frame-pointer
-- Performing Test cxx-compiler-supports-fomit-frame-pointer - Success
-- Performing Test cxx-compiler-supports-mtune-generic
-- Performing Test cxx-compiler-supports-mtune-generic - Success
-- Compiling for Linux with /bin/c++ version 4.8.5
-- Build type RelWithDebInfo
-- QWANALYSIS_CXX_FLAGS =  -pipe -fsigned-char -mtune=generic -pthread -std=c++11 -m64  -Wall
-- CMAKE_CXX_FLAGS_RELWITHDEBINFO = -O2 -g -DNDEBUG -fno-omit-frame-pointer
-- Found ET: /adaqfs/home/apar/et-12.0/src/libsrc/.Linux-x86_64/libet.so  
-- Generating evio dictionaries for ROOT 6.14.04...
-- Generating QwAnalysis dictionaries for ROOT 6.14.04...
-- Found EPICS: /adaqfs/apps/epics/lib/linux-x86_64/libca.so  
-- ***********  In Feedback Cmake
-- Compiling for Linux with /bin/c++ version 4.8.5
-- Build type RelWithDebInfo
-- QWANALYSIS_CXX_FLAGS =  -pipe -fsigned-char -mtune=generic -pthread -std=c++11 -m64  -Wall
-- CMAKE_CXX_FLAGS_RELWITHDEBINFO = -O2 -g -DNDEBUG -fno-omit-frame-pointer -fno-omit-frame-pointer
-- /adaqfs/apps/epics/lib/linux-x86_64/libca.so /adaqfs/apps/epics/lib/linux-x86_64/libcas.so /adaqfs/apps/epics/lib/linux-x86_64/libCom.so /adaqfs/apps/epics/lib/linux-x86_64/libgdd.so
-- Configuring done
-- Generating done
-- Build files have been written to: /adaqfs/home/apar/ciprian/playtime/japan/build
```
I am getting a segfault on 
```
build/qwmockdatagenerator -r 10 -e :100000 --config qwparity_simple.conf --detectors mock_detectors.map
 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f756fa87a3c in waitpid () from /lib64/libc.so.6
#1  0x00007f756fa05de2 in do_system () from /lib64/libc.so.6
#2  0x00007f7574224a84 in TUnixSystem::StackTrace (this=0xc109a8) at /raid/stage/ROOT/root-6.14.04/core/unix/src/TUnixSystem.cxx:2413
#3  0x00007f75742271bc in TUnixSystem::DispatchSignals (this=0xc109a8, sig=kSigSegmentationViolation) at /raid/stage/ROOT/root-6.14.04/core/unix/src/TUnixSystem.cxx:3644
#4  <signal handler called>
#5  0x00007f756fb02f3b in __strstr_sse42 () from /lib64/libc.so.6
#6  0x00007f7566a8e1bb in strstr (__needle=0x7f7568851785 "_ACLiC_dict", __haystack=0x0) at /usr/include/string.h:333
#7  TCling::RegisterModule (this=0xc985f8, modulename=0x0, headers=0x0, includePaths=0x0, payloadCode=0x0, fwdDeclsCode=0x0, triggerFunc=0x0, fwdDeclsArgToSkip=std::vector of length 0, capacity 0, classesHeaders=0x0, lateRegistration=true, hasCxxModule=false) at /raid/stage/ROOT/root-6.14.04/core/metacling/src/TCling.cxx:1687
#8  0x00007f75740685c2 in TROOT::InitInterpreter (this=0x7f757450ee60 <ROOT::Internal::GetROOT1()::alloc>) at /raid/stage/ROOT/root-6.14.04/core/base/src/TROOT.cxx:2114
#9  0x00007f7574068ae6 in ROOT::Internal::GetROOT2 () at /raid/stage/ROOT/root-6.14.04/core/base/src/TROOT.cxx:388
#10 0x00007f75738a8932 in TMapFile::WhichMapFile (addr=addr
entry=0xc53530) at /raid/stage/ROOT/root-6.14.04/io/io/src/TMapFile.cxx:1229
#11 0x00007f75738a8a8e in (anonymous namespace)::FreeIfTMapFile (ptr=0xc53530) at /raid/stage/ROOT/root-6.14.04/io/io/src/TMapFile.cxx:135
#12 0x00007f75705b2205 in operator delete (ptr=0xc53538) at /raid/stage/ROOT/root-6.14.04/core/newdelete/src/NewDelete.cxx:283
#13 0x00007f757406db5b in deallocate (this=0x7f757450ed10 <(anonymous namespace)::GetModuleHeaderInfoBuffer()::moduleHeaderInfoBuffer>, __p=<optimized out>) at /usr/include/c++/4.8.2/ext/new_allocator.h:110
#14 _M_deallocate (this=0x7f757450ed10 <(anonymous namespace)::GetModuleHeaderInfoBuffer()::moduleHeaderInfoBuffer>, __n=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_vector.h:174
#15 _M_emplace_back_aux<(anonymous namespace)::ModuleHeaderInfo_t> (this=0x7f757450ed10 <(anonymous namespace)::GetModuleHeaderInfoBuffer()::moduleHeaderInfoBuffer>) at /usr/include/c++/4.8.2/bits/vector.tcc:430
#16 emplace_back<(anonymous namespace)::ModuleHeaderInfo_t> (this=0x7f757450ed10 <(anonymous namespace)::GetModuleHeaderInfoBuffer()::moduleHeaderInfoBuffer>) at /usr/include/c++/4.8.2/bits/vector.tcc:101
#17 push_back (__x=<unknown type in /adaqfs/apps/ROOT/6.14-04/lib/libCore.so.6.14, CU 0x0, DIE 0x1ab68>, this=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_vector.h:920
#18 TROOT::RegisterModule (modulename=modulename
entry=0x7f757351f2ca "libNet", headers=headers
entry=0x7f75737493c0 <(anonymous namespace)::TriggerDictionaryInitialization_libNet_Impl()::headers>, includePaths=includePaths
entry=0x7f75737493a0 <(anonymous namespace)::TriggerDictionaryInitialization_libNet_Impl()::includePaths>, payloadCode=payloadCode
entry=0x0, fwdDeclCode=fwdDeclCode
entry=0x0, triggerFunc=triggerFunc
entry=0x7f75734dec80 <(anonymous namespace)::TriggerDictionaryInitialization_libNet_Impl()>, fwdDeclsArgToSkip=std::vector of length 0, capacity 0, classesHeaders=classesHeaders
entry=0x7f7573749820 <(anonymous namespace)::TriggerDictionaryInitialization_libNet_Impl()::classesHeaders>, hasCxxModule=hasCxxModule
entry=false) at /raid/stage/ROOT/root-6.14.04/core/base/src/TROOT.cxx:2591
#19 0x00007f75734decf8 in (anonymous namespace)::TriggerDictionaryInitialization_libNet_Impl () at /raid/stage/ROOT/BUILD2/net/net/G__Net.cxx:3660
#20 0x00007f75755f98f3 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#21 0x00007f75755eb15a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#22 0x0000000000000009 in ?? ()
#23 0x00007ffed007869c in ?? ()
#24 0x00007ffed00786b6 in ?? ()
#25 0x00007ffed00786b9 in ?? ()
#26 0x00007ffed00786bc in ?? ()
#27 0x00007ffed00786bf in ?? ()
#28 0x00007ffed00786c7 in ?? ()
#29 0x00007ffed00786d0 in ?? ()
#30 0x00007ffed00786e5 in ?? ()
#31 0x00007ffed00786f1 in ?? ()
#32 0x0000000000000000 in ?? ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00007f756fb02f3b in __strstr_sse42 () from /lib64/libc.so.6
#6  0x00007f7566a8e1bb in strstr (__needle=0x7f7568851785 "_ACLiC_dict", __haystack=0x0) at /usr/include/string.h:333
#7  TCling::RegisterModule (this=0xc985f8, modulename=0x0, headers=0x0, includePaths=0x0, payloadCode=0x0, fwdDeclsCode=0x0, triggerFunc=0x0, fwdDeclsArgToSkip=std::vector of length 0, capacity 0, classesHeaders=0x0, lateRegistration=true, hasCxxModule=false) at /raid/stage/ROOT/root-6.14.04/core/metacling/src/TCling.cxx:1687
#8  0x00007f75740685c2 in TROOT::InitInterpreter (this=0x7f757450ee60 <ROOT::Internal::GetROOT1()::alloc>) at /raid/stage/ROOT/root-6.14.04/core/base/src/TROOT.cxx:2114
#9  0x00007f7574068ae6 in ROOT::Internal::GetROOT2 () at /raid/stage/ROOT/root-6.14.04/core/base/src/TROOT.cxx:388
#10 0x00007f75738a8932 in TMapFile::WhichMapFile (addr=addr
entry=0xc53530) at /raid/stage/ROOT/root-6.14.04/io/io/src/TMapFile.cxx:1229
#11 0x00007f75738a8a8e in (anonymous namespace)::FreeIfTMapFile (ptr=0xc53530) at /raid/stage/ROOT/root-6.14.04/io/io/src/TMapFile.cxx:135
#12 0x00007f75705b2205 in operator delete (ptr=0xc53538) at /raid/stage/ROOT/root-6.14.04/core/newdelete/src/NewDelete.cxx:283
#13 0x00007f757406db5b in deallocate (this=0x7f757450ed10 <(anonymous namespace)::GetModuleHeaderInfoBuffer()::moduleHeaderInfoBuffer>, __p=<optimized out>) at /usr/include/c++/4.8.2/ext/new_allocator.h:110
#14 _M_deallocate (this=0x7f757450ed10 <(anonymous namespace)::GetModuleHeaderInfoBuffer()::moduleHeaderInfoBuffer>, __n=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_vector.h:174
#15 _M_emplace_back_aux<(anonymous namespace)::ModuleHeaderInfo_t> (this=0x7f757450ed10 <(anonymous namespace)::GetModuleHeaderInfoBuffer()::moduleHeaderInfoBuffer>) at /usr/include/c++/4.8.2/bits/vector.tcc:430
#16 emplace_back<(anonymous namespace)::ModuleHeaderInfo_t> (this=0x7f757450ed10 <(anonymous namespace)::GetModuleHeaderInfoBuffer()::moduleHeaderInfoBuffer>) at /usr/include/c++/4.8.2/bits/vector.tcc:101
#17 push_back (__x=<unknown type in /adaqfs/apps/ROOT/6.14-04/lib/libCore.so.6.14, CU 0x0, DIE 0x1ab68>, this=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_vector.h:920
#18 TROOT::RegisterModule (modulename=modulename
entry=0x7f757351f2ca "libNet", headers=headers
entry=0x7f75737493c0 <(anonymous namespace)::TriggerDictionaryInitialization_libNet_Impl()::headers>, includePaths=includePaths
entry=0x7f75737493a0 <(anonymous namespace)::TriggerDictionaryInitialization_libNet_Impl()::includePaths>, payloadCode=payloadCode
entry=0x0, fwdDeclCode=fwdDeclCode
entry=0x0, triggerFunc=triggerFunc
entry=0x7f75734dec80 <(anonymous namespace)::TriggerDictionaryInitialization_libNet_Impl()>, fwdDeclsArgToSkip=std::vector of length 0, capacity 0, classesHeaders=classesHeaders
entry=0x7f7573749820 <(anonymous namespace)::TriggerDictionaryInitialization_libNet_Impl()::classesHeaders>, hasCxxModule=hasCxxModule
entry=false) at /raid/stage/ROOT/root-6.14.04/core/base/src/TROOT.cxx:2591
#19 0x00007f75734decf8 in (anonymous namespace)::TriggerDictionaryInitialization_libNet_Impl () at /raid/stage/ROOT/BUILD2/net/net/G__Net.cxx:3660
#20 0x00007f75755f98f3 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#21 0x00007f75755eb15a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#22 0x0000000000000009 in ?? ()
#23 0x00007ffed007869c in ?? ()
#24 0x00007ffed00786b6 in ?? ()
#25 0x00007ffed00786b9 in ?? ()
#26 0x00007ffed00786bc in ?? ()
#27 0x00007ffed00786bf in ?? ()
#28 0x00007ffed00786c7 in ?? ()
#29 0x00007ffed00786d0 in ?? ()
#30 0x00007ffed00786e5 in ?? ()
#31 0x00007ffed00786f1 in ?? ()
#32 0x0000000000000000 in ?? ()
===========================================================


Fatal in <operator delete>: storage area overwritten
aborting
Abort (core dumped)
```

**Comment by paulmking** [comment]
The type of immediate crash you are seeing is suggestive of the ROOT libNew being in the wrong position.  Can you post the ldd result for qwmockdatagenerator and qwparity?

**Comment by paulmking** [comment]
@wdconinc On adaq3, the default build of this branch results in a crash doing `./build/qwparity --help`.  What was the environment on your develop machine?  Did you do something to change the link order of the libNew?

**Comment by wdconinc** [comment]
I did not have any other changes to any files in the branch. I'm on gcc8, root 6.16 (can test with 6.14). I didn't manipulate my environment in any specific way. Is an LD_LIBRARY_PATH maybe causing this? I'll try to look into it this am.

**Comment by cipriangal** [comment]
Here is my path and lib path:
```
[apar@adaq3 ~/ciprian/playtime/japan/build]$ echo $LD_LIBRARY_PATH 
/adaqfs/apps/ROOT/6.14-04/lib:/adaqfs/home/apar/et-12.0/src/libsrc/.Linux-x86_64/:~apar/misclib:/adaqfs/coda/2.6.2/Linux/lib:/adaqfs/home/adaq/CMLOG/CMLOG-R2_1-PROD-1/lib/Linux:/usr/X11R6/lib:/adaqfs/appsroot/cdev_1.7.5/lib/Linux:/adaqfs/apps/analyzer/lib:/adaqfs/apps/ROOT/6.12-06/lib:/adaqfs/apps/lib:/adaqfs/coda/2.6.2/cMsg/Linux-i686/lib:/adaqfs/coda/2.6.2/Linux/lib:/adaqfs/coda/2.6.2/cdev_1.7.5/lib/Linux
[apar@adaq3 ~/ciprian/playtime/japan/build]$ echo $PATH
/adaqfs/apps/ROOT/6.14-04/bin:/adaqfs/coda/2.6.2/afecs/bin:/adaqfs/home/adaq/java/jre1.8.0_144/bin:/adaqfs/home/apar/bin:/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin:/adaqfs/coda/2.6.2/Linux/bin:/adaqfs/home/apar/bin:/adaqfs/home/apar/bin/Linux:/apps/bin:/usr/local/bin:/usr/sbin:/usr/bin/X11:/opt/SUNWspro/bin:/opt/ansic/bin:/opt/aCC/bin:/opt/fortran/bin:/opt/fortran90/bin:/opt/langtools/bin:/usr/ccs/bin:/usr/bin:/bin:/usr/dt/bin:/usr/openwin/bin:/etc:/usr/etc:/usr/xpg4/bin:/usr/ucb:/usr/bsd:/sbin:/usr/proc/bin:/opt/imake/bin:.:/usr/local/gnu-ppc/bin
```

In case you want to just run what I have:
log into apar, go to ciprian, source setupEnv.csh, go to playtime/japan

**Comment by wdconinc** [comment]
Ok, reproduced this on the docker image (with singularity) on both this branch and on develop. Linking in libNew.so is not necessary if we just preload. Using `singularity pull docker://jeffersonlab/japan:develop` we get correct results with `qwparity --help` but an immediate crash with `LD_PRELOAD=`root-config --libdir`/libNew.so build/qwparity --help`

**Comment by wdconinc** [comment]
Not sure how to show backticks inside a backtick clause in github markdown... :-)

**Comment by wdconinc** [comment]
Status update:

1. Using the container at `singularity pull docker://jeffersonlab/japan:develop` we can reproduce the crash with the pre-built qwparity at $JAPAN
```
LD_PRELOAD=`root-config --libdir`/libNew.so build/qwparity -h
```
while just running `qwparity -h` works. This is using ROOT 6.14.04 and gcc 4.8.5.

2. Using the same container we can also built our own version of qwparity using the ROOT and gcc version in the container and reproduce the crash with LD_PRELOAD.

2. Using gcc-8 and ROOT 6.14.06 on ubuntu 18.10 using LD_PRELOAD on develop works.

3. Using gcc-5 and ROOT 6.14.06 on ubuntu 18.10 fails to link due to boost::regex (don't care to debug that for now)

4. Using gcc-6 and ROOT 6.14.06 on ubuntu 18.10 works.

libstdc++.so.6 is the same major/minor version on both container and ubuntu 18.10 (6.0.19 vs 6.0.25).

I think the next step is to go back to the hprod and hcons examples and see if those work.

**Comment by wdconinc** [comment]
```
cd rootScripts/mapfile
g++ hprod.C -o hprod `root-config --cflags --ldflags --libs`
LD_PRELOAD=`root-config --libdir`/libNew.so ./hprod
```
also fails right away when compiling in the container.

**Comment by wdconinc** [comment]
This literally crashes trying to find `__needle` in `__haystack`:
```
__extern_always_inline const char *
strstr (const char *__haystack, const char *__needle) __THROW
{
  return __builtin_strstr (__haystack, __needle);
}
```
in /usr/include/string.h:333.

**Comment by cipriangal** [comment]
maybe this is a sign ...

**Comment by wdconinc** [comment]
Minimal example:
```
echo "int main() { }" | g++ -x c++ - `root-config --new --cflags --ldflags --libs` && ./a.out
```
crashes with the same error. Nothing to do with mapfile at all.

**Comment by wdconinc** [comment]
Maybe it's that new tattoo...

image

**Comment by wdconinc** [comment]
Oi, this works!
```
echo "int main() { }" | g++ -x c++ - `root-config --new --libs --glibs` && ./a.out
```

**Comment by wdconinc** [comment]
The following now functions correctly(*) on the farm with JLab CE 2.3.
```
build/qwmockdatagenerator -r 10 -e :100000 --config qwparity_simple.conf --detectors mock_detectors.map
build/qwparity -r 10 --config qwparity_mapfile.conf
```

(*) Still crashes on close.

**Comment by hansenjo** [comment]
Likely related: https://sft.its.cern.ch/jira/browse/ROOT-9240

**Comment by wdconinc** [comment]
Yeah, I saw that too. I soured on reporting bugs to the ROOT team (or helping them with debugging) a long time ago. Although, I have to admit that their attitude has improved now that leadership has changed...

**Comment by wdconinc** [comment]
Hate to reopen this. Using ROOT's --new may not be appropriate for all cases... In my personal code on ADC18 I have a perfectly fine QwOut statement that segfaults when linked against ROOT libNew but runs fine otherwise. Not sufficient for a bug report (nor is it in committed code) but something to keep in mind.

**Pull request merged**
