### PR TITLE
Feature: use system FindROOT.cmake instead of our own

### PR DESCRIPTION
**Pull request by wdconinc**
This partially(*) resolves issue #41 since the system FindROOT.cmake (actually ROOTConfiguration.cmake) is smarter about dependencies (at least for ROOT 6.14). This may need testing on 5.34 if someone thinks we need to keep that as a dependency...

(*) It only fixes the dictionary generation. Since it still pulls git info every time, we trigger a rebuild each time. I think the time stamp in pullgitinfo.py causes that (`Generated at Tue Nov 20 10:41:39 EST 2018`)... We can get rid of that. We can also use multiline string literals instead of the yucky gGitInfoStr binary blob:
```
const char* gGitInfo = R"gitinfo(
text text text
)gitinfo";

### CODE REVIEW

**Comment by wdconinc** [comment]
Also, note that it does still track dictionary dependencies correctly. `touch evio/include/THaCodaData.h` will trigger a regeneration and rebuild of those dictionaries.

**Comment by paulmking** [comment]
This supposes that the system FindROOT.cmake is working.  Depending on how you have ROOT installed, it may not be working...

On my devel machines at OU (Centos 7.5 with ROOT6.14-04 installed from EPEL, but not all sub-packages installed), cmake fails to find all the components that FindROOT.cmake expects.  I'll try getting all the sub-packages and see if that works.

I have similar issues on adaq using /adaqfs/apps/ROOT/6.12-06.  I haven't tried yet on ifarm.

**Comment by wdconinc** [comment]
It is true that it requires that you have ROOT installed in a standard location or that you tell cmake where to find ROOT. The previous solution had that functionality implemented in an ad hoc way that may have worked.

This branch works for me on the ifarm with JLab CE 2.0 and higher (which is ROOT 6.08). JLab CE 1.3 is not supported anymore. I don't have access to adaq to test.

**Comment by wdconinc** [comment]
I'll admit that I don't know exactly how cmake finds the correct ROOTConfiguration.cmake in my case (https://cmake.org/cmake/help/v3.0/command/find_package.html is dense even after a hundred times). We could work around it specifying HINTS in find_package.

**Comment by cipriangal** [comment]
I can confirm that as of now a fresh copy of this branch will not finish cmake on apar@adaq3

Interestingly if I set ROOTSYS to /adaqfs/apps/ROOT/6.14-04 and do not include the FindRoot.cmake we had before it goes off on it's own and identifies root 6.12-06 and complains that:
```
CMake Error at /adaqfs/apps/ROOT/6.12-06/cmake/ROOTConfig-targets.cmake:1050 (message):
  The imported target "ROOT::hist2workspace" references the file

     "/adaqfs/apps/ROOT/6.12-06/bin/hist2workspace"

```

I will talk to someone here to understand why this executable doesn't exist.

**Comment by cipriangal** [comment]
I talked to Ole about this issue and apparently he manually renamed the hist2workspace binary because it was interfering when he was typing the history command :)). He will put it back and he suggests we use our own FindRoot.cmake in the package instead of relying on the system. An example is in the podd analyzer (https://github.com/hansenjo/analyzer/blob/master/cmake/Modules/FindROOT.cmake -- i think this is the one he was talking about).

**Comment by wdconinc** [comment]
This is now working on at least one system (my laptop). It is heavily borrowed from the FindROOT in podd so presumably more maintainable than our own homegrown system.

I don't have access to adaq yet, so someone else will have to check there.

**Comment by wdconinc** [comment]
@paulmking I enabled QwDatabase again mainly to test whether MySQL++ gets linked correctly. I couldn't test ET since I don't have that on my system.

**Comment by wdconinc** [comment]
I wasn't able to test the "not found mysqlpp" path because I need that on my system :-) I suspect my list remove_item logic is somehow not working. I also don't have THaEtClient since not on a system with ET installed. I'm waiting for word back from CC on my 2fa token... then I can test on adaq.

Suspicion for both QwDatabase and THaEtClient is that manipulation of the list which was created by file(GLOB) using a relative path must be done using absolute paths (GLOB probably turns relative into absolute paths).

**Comment by cameronc137** [comment]
The ET warning may have something to do with separately installing the 64 bit version of ET in ~apar/et-12.0/? I think @rwmichaels would be able to illuminate this more than me.

**Comment by cipriangal** [comment]
@wdconinc : I mean that include files seems to be here:
https://github.com/JeffersonLab/japan/blob/master/evio/include/THaEtClient.h

**Comment by wdconinc** [comment]
As for the ROOT version. It should use the root-config in $ROOTSYS/bin/ to find the version and prefix, etc, but it could be that if you have a different root-config in your $PATH it is preffered. e.g. $ROOTSYS to 6.14, but $ROOTSYS/bin not in path, and therefore root-config still resolves to a 6.12 version. Anyway, hard to debug this without access to the system.

**Comment by wdconinc** [comment]
But, lest it be overlooked, this new FindROOT from Hall A does indeed resolve the original reason for this branch: the dictionaries are not re-compiled on every invocation of make, they have the correct dependencies on the headers they derive from, and they get installed (along with pcm files) in the right places.

**Comment by cipriangal** [comment]
@wdconinc : not sure about the root-config/PATH. I have:
```
[apar@adaq3 ~/ciprian/playtime/japan/build]$ which root-config 
/adaqfs/apps/ROOT/6.14-04/bin/root-config
[apar@adaq3 ~/ciprian/playtime/japan/build]$ echo $PATH
/adaqfs/apps/ROOT/6.14-04/bin:/adaqfs/coda/2.6.2/afecs/bin:/adaqfs/home/adaq/java/jre1.8.0_144/bin:/adaqfs/home/apar/bin:/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin:/adaqfs/coda/2.6.2/Linux/bin:/adaqfs/home/apar/bin:/adaqfs/home/apar/bin/Linux:/apps/bin:/usr/local/bin:/usr/sbin:/usr/bin/X11:/opt/SUNWspro/bin:/opt/ansic/bin:/opt/aCC/bin:/opt/fortran/bin:/opt/fortran90/bin:/opt/langtools/bin:/usr/ccs/bin:/usr/bin:/bin:/usr/dt/bin:/usr/openwin/bin:/etc:/usr/etc:/usr/xpg4/bin:/usr/ucb:/usr/bsd:/sbin:/usr/proc/bin:/opt/imake/bin:.:/usr/local/gnu-ppc/bin
```

Fixed the compile error with absolute paths (although I am running into a linking error now). 

The "grep error" is generated from 
https://github.com/JeffersonLab/japan/blob/feature-cmake-use-system-findROOT/CMakeLists.txt#L114

I'll keep working on this for a while and push any successful changes before I head off.

**Comment by cipriangal** [comment]
@paulmking : the grep error i pointed out seems to come from:
https://github.com/JeffersonLab/japan/blob/feature-cmake-use-system-findROOT/evio/CMakeLists.txt#L42
and that is as @wdconinc  suggested because at line https://github.com/JeffersonLab/japan/blob/feature-cmake-use-system-findROOT/evio/CMakeLists.txt#L26 we add relative paths instead of absolute (as glob converts).

If I fix this it complains that it can't find the LinkDef.h file for EtClient and tries to do "TOUCH" which then results in an error from cmake.
```
CMake Error at evio/CMakeLists.txt:56 (file):
  file does not recognize sub-command TOUCH
```

I 'think' I can fix it if i remove this block (https://github.com/JeffersonLab/japan/blob/feature-cmake-use-system-findROOT/evio/include/THaEtClient.h#L90) . Doest that sound reasonable? 

That way it will never go into the if block for the touch at line:
https://github.com/JeffersonLab/japan/blob/feature-cmake-use-system-findROOT/evio/CMakeLists.txt#L50
but maybe that is something we also want to fix!?

**Comment by wdconinc** [comment]
file(TOUCH) may require a more recent cmake. In any case, creating a dictionary without LinkDef isn't supported by this FindROOT.cmake (nor generally what you want). I'd recommend creating a simple LinkDef file with the usual pragma lines.

**Comment by cipriangal** [comment]
my proposal would not attempt to create a dictionary. It really looks like the only thing this was used for is the online analysis client, which we will probably never use because we are doing the analysis and putting it into a memory resident root file, right!?

**Comment by cipriangal** [comment]
@wdconinc : it seems the new CMakeList.txt does not do everything the Makefile used to do before:
[linkOut.txt](https://github.com/JeffersonLab/japan/files/2769888/linkOut.txt)

**Comment by cipriangal** [comment]
I'll wait to fix the two things remaining before pushing the fixes i have so far.
* if EtClient needs an LinkDef
* the Makefile->CMakeLists conversion

**Comment by wdconinc** [comment]
@cipriangal  Of course, the ET linking above is untested (since I don't have ET on my laptop), but I think that may fix the linker errors.

**Comment by cipriangal** [comment]
compiles and links properly. i'll try to run it over a file and if nothing breaks we should be good to go. For the remaining FindROOT issue (where it find 6.12 when I have the correct path and ROOTSYS for 6.14) i'll will have to ask Ole about.

**Comment by wdconinc** [comment]
Was that with empty LinkDef and/or the ClassImp commented out? In particular the second one my cause that.

**Comment by cipriangal** [comment]
nope .. this is with a fresh copy of what is in the repo now.

**Comment by wdconinc** [comment]
Let's hope I get a 2fa token tomorrow, then I can look at this.

**Comment by paulmking** [comment]
This branch is now working for me on both my OU devel machine and on adaq.  I verified on apar@adaq3 that the online mode tries to connect to the ET system, but didn't have the DAQ running to do a full test of that.

**Pull request merged**
