### PR TITLE
Bugfix online epicscheck

### PR DESCRIPTION
**Pull request by paulmking**
This should be the last thing needed to demonstrate we have completed issue #16.

To test the functionality of connecting to the 2ET system, you need to be on apar@adaq3, then:
1)  Start coda and start a run
2)  Execute `./build/qwparity --config prex.conf --add-config online_apar.conf `.  This should connect to the ET system and you should see helicity event processing messages for the first 30 patterns.  The event processing rate should match the CODA rate.
3)  In the ROOT file directory, a file `prexALL_0.root` should be created and its size should be growing.
4)  Use ctrl-C to stop the analysis process.  The rootfile should remain, and should contain the usual trees, if you inspect the contents.

### CODE REVIEW

**Comment by paulmking** [comment]
I have verified the outputs are consistent for this branch and the current develop branch on both mock data and PREX data taken during APEX.

Testing on PREX datastream on apar@adaq3:
Execute `./build/qwparity --config prex.conf -r 1241 --print-runningsum > tmp_out` then `diff tmp_out ~/pking/referenceData/output_develop-ecbca5a_1241.txt`.  There are no substantive changes between the two (only process related differences, like filepaths, time per event, etc.).

Testing on mock data on apar@adaq3:
First `unsetenv QW_DATA` so that the mock data file will be created in your local directory.  Create a mock data file using `./build/qwmockdatagenerator --config qwparity_simple.conf --detectors mock_detectors.map -r 10 -e 1:10000`, then analyse it with `./build/qwparity --config qwparity_simple.conf --detectors mock_detectors.map -r 10 -e 1:10000 --print-runningsum > tmp_out`.  Compare the output file to the reference: `diff tmp_out ~/pking/referenceData/output_develop-ecbca5a_10.txt `; again only process related difference should appear.

**Comment by paulmking** [comment]
Using the "--add-config online_apar.conf" on the command line ends up hiding the add-config for the low-bank-IDs which is in the prex.conf file.
I'm working on a patch to discover both added config files.

**Comment by cipriangal** [comment]
I'll take a look at this when the DAQ is not being used (maybe tonight or tomorrow morning).

**Comment by wdconinc** [comment]
That's because add-config on the command line overrides the add-config in the file (intentionally, so you can also override other commands). I thought we had a different way of including conf file snippets?

**Comment by paulmking** [comment]
Defining the "add-config" option with "composing" allows the command line and config files to both be picked up.

**Comment by paulmking** [comment]
Full testing of online mode was done during run 1359 using `./build/qwparity --config prex.conf --add-config online_apar.conf`.  Analyzer behavior seems to be correct.

**Pull request merged**
