### PR TITLE
Feature: RPATH for installed binaries

### PR DESCRIPTION
**Pull request by wdconinc**
This will require testing on a system where rpaths actually make a difference, like adaq or apar. I don't have access to that right now. I'll see if I can rig up something on the farm... but some of you may have the systems in place already.

I'm interested in looking at what the following returns in followup bug reports:
```
chrpath -l lib/libQwAnalysis.so
chrpath -l bin/qwparity
```

### CODE REVIEW

**Comment by cipriangal** [comment]
This compiles just fine on apar@adaq3 but chrpath is not installed on the system. Will ask @rwmichaels about it.

**Comment by paulmking** [comment]
I had also tried this on apar@adaq3, and found that if the ROOT path wasn't in the LD_LIBRARY_PATH after compilation, I got errors.  It seems like it didn't actually have the rpath compiled in?

**Comment by rwmichaels** [comment]
Ask Ole about chrpath or what you need -- if it is to be "installed on the system" he will be happy to do it, I think.  But if it is a change to "apar" login, then feel free to do it if you know how.  As for me, I will be incredibly busy for 2 weeks because of the APEX preparations.


Dr. Robert Michaels

Staff Scientist, Jefferson Lab

http://userweb.jlab.org/~rom

________________________________

**Comment by wdconinc** [comment]
This is indeed not working yet (maybe after recent build system changes). Now I get interesting mixtures such as:
```
===========================================================
#5  TCling::TCling (this=0x1eda740, name=<optimized out>, title=<optimized out>, argv=0x0) at /group/halla/analysis/rootbuild/ifarm1401/root-6.14.04/core/metacling/src/TCling.cxx:1145
#6  0x00007f69218ce9d4 in CreateInterpreter (interpLibHandle=<optimized out>, argv=0x0) at /group/halla/analysis/rootbuild/ifarm1401/root-6.14.04/core/metacling/src/TCling.cxx:616
#7  0x00007f692ed642d8 in TROOT::InitInterpreter (this=0x7f692f226f40 <ROOT::Internal::GetROOT1()::alloc>) at /group/halla/analysis/rootbuild/ifarm1402/root-6.12.06/core/base/src/TROOT.cxx:2047
#8  0x00007f692ed64736 in ROOT::Internal::GetROOT2 () at /group/halla/analysis/rootbuild/ifarm1402/root-6.12.06/core/base/src/TROOT.cxx:385
#9  0x00007f692edd969d in TApplication::TApplication (this=0x1eb6a80, appClassName=0x405be4 "Qweak-Root Analyzer", argc=0x7fff137d84bc, argv=0x7fff137d86b8, numOptions=0) at /group/halla/analysis/rootbuild/ifarm1402/root-6.12.06/core/base/src/TApplication.cxx:156
#10 0x00007f692cb59e61 in TRint::TRint (this=0x1eb6a80, appClassName=<optimized out>, argc=<optimized out>, argv=<optimized out>, options=<optimized out>, numOptions=<optimized out>, noLogo=false) at /group/halla/analysis/rootbuild/ifarm1402/root-6.12.06/core/rint/src/TRint.cxx:146
#11 0x00007f692ff35e0a in QwRint::QwRint (this=0x1eb6a80, appClassName=<optimized out>, argc=<optimized out>, argv=<optimized out>, options=<optimized out>, numOptions=<optimized out>, noLogo=false) at /home/wdconinc/git/japan/Analysis/src/QwRint.cc:20
#12 0x0000000000404090 in main (argc=1, argv=0x7fff137d86b8) at /home/wdconinc/git/japan/Analysis/main/QwRoot.cc:23
===========================================================
```

Test case (bash):
```
mkdir build_2.2 && pushd build_2.2
export JLAB_VERSION=2.2 && source ${JLAB_ROOT}/${JLAB_VERSION}/ce/jlab.sh
cmake .. && make -j 8
popd
mkdir build_2.3 && pushd build_2.3
export JLAB_VERSION=2.3 && source ${JLAB_ROOT}/${JLAB_VERSION}/ce/jlab.sh
cmake .. && make -j 8
popd
pushd build_2.2
./qwroot
```

This all should open a session with the correct ROOT version.

**Comment by wdconinc** [comment]
Unsetting $LD_LIBRARY_PATH seems to have fixed it... now, the question is whether we can realistically unset $LD_LIBRARY_PATH on adaq...

**Comment by wdconinc** [comment]
Yeah, I think this just works now as expected in HEAD on develop. After building the above procedure, both the following result in appropriate info:
```
~/git/japan/build_2.2/qwparity --version
~/git/japan/build_2.3/qwparity --version
```

I suggest closing this and deleting branch feature-rpath. If there are future problems with rpath a new bug may need to be opened.

**Comment by wdconinc** [comment]
On apar@adaq3 I have develop HEAD compiled with ~/wdconinc/setup_japan_6.{08,10,12,14}.tcsh in ~/wdconinc/japan/build_6.{08,10,12,14}/. Only after unset LD_LIBRARY_PATH does 
```
 ~/wdconinc/japan/build_6.08/qwparity --version
```
return the correct output. Otherwise (default) I get
```
[wdconinc@hallgw2]~% ssh apar@adaq3
apar@adaq3's password: 
Last login: Wed Jan 30 10:15:46 2019 from hallgw1.jlab.org
Welcome to the Hall A DAQ cluster (adaq3)
CentOS Linux release 7.5.1804 (Core) 
Kernel 3.10.0-862.11.6.el7.x86_64 on a 12-processor 2.4GHz x86_64

[apar@adaq3 ~]$ ~/wdconinc/japan/build_6.08/qwparity --version
Error: Environment variable QW_PRMINPUT undefined!
Warning: Using current directory instead.
. is a directory; adding it to the search path
Error: Environment variable QWANALYSIS undefined!
Warning: Using current directory instead.
./Parity/prminput doesn't exist.
Error: Environment variable QWANALYSIS undefined!
Warning: Using current directory instead.
./Analysis/prminput doesn't exist.
Adding user-defined configuration file qwparity.conf
Adding user-defined configuration file qweak_mysql.conf
Config files:
qwparity.conf
qweak_mysql.conf
Fatal in <TROOT::InitInterpreter>: cannot load library /adaqfs/apps/ROOT/6.12-06/lib/libCling.so: undefined symbol: _ZN4ROOT10gCoreMutexE
[apar@adaq3 ~]$ echo $LD_LIBRARY_PATH 
/adaqfs/home/apar/et-12.0/src/libsrc/.Linux-x86_64/:~apar/misclib:/adaqfs/coda/2.6.2/Linux/lib:/adaqfs/home/adaq/CMLOG/CMLOG-R2_1-PROD-1/lib/Linux:/usr/X11R6/lib:/u/apps/root/5.34.36/root/lib:/adaqfs/appsroot/cdev_1.7.5/lib/Linux:/u/apps/root/5.34.36/root/lib:/adaqfs/apps/analyzer/lib:/adaqfs/apps/ROOT/6.12-06/lib:/adaqfs/apps/lib:/adaqfs/coda/2.6.2/cMsg/Linux-i686/lib:/adaqfs/coda/2.6.2/Linux/lib:/adaqfs/coda/2.6.2/cdev_1.7.5/lib/Linux
```
even though the only ROOT in $LD_LIBRARY_PATH is 5.34.36. Strange that it somehow picks up 6.12 over 5.34.36 (in LD_LIBRARY_PATH) and 6.08 (in rpath as per `readelf -d ~/wdconinc/japan/build_6.08/qwparity`).

In any case, I think the handling of rpath by japan is correct. The remaining issue may be a adaq environment issue.

**Comment by wdconinc** [comment]
I realized that `~/wdconinc/japan/build_6.08/qwparity --version` is not a good test. It just prints a string that is stored at compile time... But still, if it succeeds it is likely that it found the right libraries. `~/wdconinc/japan/build_6.08/qwroot` and checking the splash screen version is probably a better test.

**Comment by hansenjo** [comment]
I just tested this on apar@adaq3 as follows (bash shell):

```
$ cd ~apar/ole/japan
$ git checkout feature-rpath
$ export LD_LIBRARY_PATH=/adaqfs/home/apar/et-12.0/src/libsrc/.Linux-x86_64:/adaqfs/apps/analyzer/lib:/adaqfs/apps/lib
$ export PATH=/adaqfs/home/apar/bin:/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin:/apps/bin:/usr/local/bin
$ source /adaqfs/apps/ROOT/6.14-04/bin/thisroot.sh
$ mkdir ../build && cd ../build
$ cmake ../japan
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
--     Install-prefix was at default -> forcing it to the source-dir
--     Use -DCMAKE_INSTALL_PREFIX=/usr/local to set to something else
-- System name Linux
-- Found ROOT 6.14/04 in /adaqfs/apps/ROOT/6.14-04
-- Looking for MySQL and MySQL++ libraries.
--   Found MySQL++ library at /lib64/libmysqlpp.so
--   The "__USE_DATABASE__" flag is commented out in CMakeLists.txt; database support is DISABLED.
--   Forcing MYSQLPP_LIBRARIES to "".
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   system
--   regex
Foud ET:  /adaqfs/home/apar/et-12.0/src/libsrc,  /adaqfs/home/apar/et-12.0/src/libsrc/.Linux-x86_64/libet.so
-- Found ET: /adaqfs/home/apar/et-12.0/src/libsrc  
Generating evio dictionaries for ROOT 6.14/04...
Generating QwAnalysis dictionaries for ROOT 6.14/04...
-- Configuring done
-- Generating done
-- Build files have been written to: /adaqfs/home/apar/ole/build

$ make -j8
.... compiles for 1-2 minutes ...

$ ./qwparity --version
Error: Environment variable QW_PRMINPUT undefined!
Warning: Using current directory instead.
. is a directory; adding it to the search path
Error: Environment variable QWANALYSIS undefined!
Warning: Using current directory instead.
./Parity/prminput doesn't exist.
Error: Environment variable QWANALYSIS undefined!
Warning: Using current directory instead.
./Analysis/prminput doesn't exist.
Adding user-defined configuration file qwparity.conf
Adding user-defined configuration file qweak_mysql.conf
Config files:
qwparity.conf
qweak_mysql.conf

 Qweak Analysis Framework : ./qwparity
 * GIT info: origin	https://github.com/JeffersonLab/japan.git (fetch)
origin	https://github.com/JeffersonLab/japan.git (push)
commit 6f81c3cbfd5cc78cfb7747c92a528c119c9330e0
Author: Wouter Deconinck <wdconinc@gmail.com>
Date:   Tue Nov 20 11:30:44 2018 -0500

    Use correct Boost_LIBRARY_DIRS (with -S)
    
    Also, modern Boost and CMake installs don't suffer from the 2.8.4 bug
    anymore.
## feature-rpath
  ROOT version 6.14/04
 cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

Generated at Fri Feb  1 17:20:41 EST 2019
Source dir /adaqfs/home/apar/ole/japan
Build  dir /adaqfs/home/apar/ole/build

 * ROOT 6.14/04, Date : 20180823, GIT : v6-14-04 tags/v6-14-04

$ chrpath -l ./qwparity
./qwparity: RPATH=/adaqfs/home/apar/ole/build:/adaqfs/home/apar/et-12.0/src/libsrc/.Linux-x86_64:

bash-4.2$ chrpath -l ./libQwAnalysis.so 
./libQwAnalysis.so: RPATH=/adaqfs/home/apar/ole/build:::::::::::::::::::::::::::::::::::::::::::::
```

I don't get the errors about undefined environment variables with the master branch.

It looks like RPATH is working as it should.

`PATH` and `LD_LIBRARY_PATH` of the apar account are definitely not set right, though. There's a ton of ancient cruft in both.

**Comment by wdconinc** [comment]
@hansenjo Thanks for testing! I think that at this point the branch feature-rpath has been outpaced by the develop branch. I think that the develop branch should have rpath set correctly, though, based on my testing. Could you test that too? If develop works fine, I think we will just get rid of this branch.

**Comment by wdconinc** [comment]
We won't merge this in since it seems to work fine in the develop branch after the new cmake build system was pulled in. Closing PR now. Branch will be deleted in 3 days.

**Pull request closed without merging**
